language: ruby
language: rake
language: node_js
rvm:
 - 2.2
 - jruby
 
 
  language: node_js
   - "stable"
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'